# Generated by Django 5.0.7 on 2024-11-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
